
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 130
#define YY_END_OF_BUFFER 131
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[511] =
    {   0,
        0,    0,    0,    0,    0,    0,  131,  129,    2,    1,
        1,   89,  129,  109,  106,  129,   76,   77,  104,  102,
       81,  103,   83,  105,  124,  124,   92,   80,   88,   86,
       87,   91,   84,   72,   72,   74,   75,  108,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   79,  107,   78,
       90,    4,    5,    5,    7,    9,    7,    2,    1,    1,
        1,   97,    0,  126,    0,  120,   98,  117,    0,    0,
      115,  100,  113,  101,  114,   93,    0,  125,    6,    3,
      116,  125,  124,    0,    0,  125,    0,  124,    0,    0,

        0,  124,    0,   85,  110,   96,   94,   95,  111,   72,
       72,   72,   73,  119,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   51,   72,   72,   72,   72,   72,   72,
       44,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   64,   72,   72,   72,   72,   72,   72,   72,  118,
       99,    5,    8,    8,   10,  126,    0,    0,    0,  127,
        0,    0,   82,  125,  125,    0,    0,  125,    0,  124,
      124,  124,    0,    0,  124,    0,  125,    0,  124,  124,
      124,  124,    0,  124,  121,  122,  112,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   47,   72,   72,   15,   72,
       72,   72,   25,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   63,   72,   72,   72,   72,
       72,    0,    0,    0,    0,    0,    0,  125,  125,    0,
        0,  125,  124,  124,  124,    0,  125,  125,    0,    0,
        0,  124,  124,  124,    0,    0,  124,  124,    0,  124,
      124,    0,  124,    0,  123,   72,   72,   72,   72,   72,
       72,   13,   12,   72,   72,   72,   72,   45,   72,   72,

       72,   72,   72,   72,   72,   72,   16,   72,   72,    0,
       70,   68,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   22,   72,   72,
       52,   56,   19,   72,   72,   66,   72,    0,    0,  125,
        0,  125,    0,  124,  124,    0,    0,    0,    0,  125,
      124,  124,    0,   72,   72,   72,   72,   72,   50,   27,
       72,   72,   72,   72,   72,   53,   24,   17,   72,   72,
       72,   72,   72,    0,   55,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   14,   72,   72,   21,   72,
       72,   72,   72,   46,   58,    0,    0,    0,    0,    0,

        0,  125,  125,    0,   26,   72,   72,   43,   72,   72,
       72,   18,   72,   72,   72,   29,   72,   59,   40,    0,
       72,   72,   72,   72,   72,   33,   69,   72,   48,   60,
       31,   72,   72,   42,   72,   72,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   72,   11,   72,   37,
       54,   20,   72,   72,    0,   28,   62,   35,   72,   72,
       72,   72,   72,   72,   72,   72,    0,    0,    0,    0,
        0,   36,   49,   72,   72,    0,   72,   65,   57,   41,
       72,   72,   72,   38,  128,    0,   72,   72,    0,   34,
       72,   32,   72,    0,   30,   23,   61,   72,   67,    0,

       72,    0,   39,    0,    0,    0,    0,    0,   71,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   21,   21,   21,   21,   22,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   30,   32,   33,   32,
       34,   34,   34,   34,   34,   35,   34,   34,   34,   36,
       34,   34,   37,   34,   34,   34,   34,   38,   34,   34,
       39,   40,   41,   42,   43,    1,   44,   45,   46,   47,

       48,   49,   50,   51,   52,   34,   53,   54,   55,   56,
       57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
       67,   68,   69,   70,   71,   72,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    6,
        6,    6,    1,    1,    1,    1,    1,    1,    1,    6,
        6,    6,    6,    7,    8,    9,    7,    7,    1,    1,
        1,    1,    9,    6,    6,    6,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    9,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[522] =
    {   0,
        0,    0,   70,   72,   74,   75,  994,  995,  991,   76,
       78,  966,   77,  965,   76,  950,  995,  995,  963,   72,
      995,   73,   73,   84,  102,  153,  965,  995,   78,  961,
       79,  995,  995,    0,   45,  945,  995,  959,   52,   59,
       57,   79,   75,  100,   76,  927,  926,   98,  924,  116,
      933,  115,  102,  919,   71,   87,  927,  995,  117,  995,
      995,  995,  995,  975,  995,  995,  153,  975,  177,  180,
      186,  995,  152,  970,  197,  995,  995,  995,  966,  254,
      995,  995,  995,  995,  995,  995,  958,  299,  995,  995,
      995,  191,  333,  201,  175,  995,  212,  995,  957,  246,

      179,  258,  263,  995,  946,  995,  995,  995,  178,    0,
      911,  909,  995,  995,  908,  907,  910,  918,  903,  920,
      919,  906,  912,  897,  898,  133,  904,  901,  899,  895,
        0,  896,  146,  897,  905,  889,  885,  893,  894,  899,
      900,  885,  191,  899,  245,  899,  885,  185,  883,  884,
       96,    0,   46,  891,  878,  174,  885,  874,  887,  995,
      995,  995,  995,  235,  995,  995,  932,  305,  316,  995,
      277,  320,  995,    0,  995,  370,  341,  375,  391,    0,
        0,  995,  407,  412,  401,  351,  419,    0,  429,  438,
      428,    0,  455,  464,  995,  995,  907,  880,  869,  868,

      881,  874,  883,  878,  865,  863,  861,  878,  876,  872,
      862,  870,  856,  872,  871,    0,  197,  852,    0,  863,
      849,  859,    0,  895,  855,  852,  854,  851,  841,  207,
      850,  846,  839,  838,  846,  839,  836,  845,  848,  849,
      833,  836,  836,  843,  829,    0,  842,  844,  833,  835,
      831,  246,  381,  250,  396,  875,  470,  481,    0,  475,
      490,  501,  435,  496,  995,  269,  533,  995,  516,  321,
      234,  526,    0,  995,  553,  551,    0,    0,  570,  559,
      577,  290,    0,  579,  995,  827,  834,  821,  820,  831,
      825,    0,    0,  816,  824,  812,  820,    0,  813,  816,

      823,  816,  807,  820,  807,  822,    0,  811,  800,  802,
        0,  801,  817,  808,  815,  810,  805,  804,  795,  802,
      793,  804,  789,  798,  803,  788,  796,    0,  781,  784,
        0,    0,    0,  782,  795,    0,  795,  523,  543,  585,
      605,  617,  622,  611,  632,  424,  521,  575,  637,  650,
      643,  655,  461,  791,  775,  785,  763,  769,    0,    0,
      746,  747,  752,  730,  744,    0,    0,    0,  700,  692,
      695,  702,  701,  697,    0,  694,  681,  679,  694,  692,
      689,  687,  673,  675,  683,    0,  683,  666,    0,  667,
      659,  667,  662,    0,    0,  706,  699,  299,  287,  697,

      673,  689,  995,  704,    0,  688,  656,    0,  640,  632,
      632,    0,  631,  630,  641,    0,  642,    0,    0,  643,
      637,  623,  635,  619,  632,    0,    0,  615,    0,    0,
        0,  604,  595,    0,  193,  593,  639,  625,  337,  615,
      372,  613,  742,  746,  429,  559,  553,    0,  566,    0,
        0,    0,  554,  560,  539,    0,    0,    0,  537,  520,
      499,  500,  500,  487,  489,  484,  519,  750,  511,  500,
      453,    0,    0,  443,  404,  412,  405,    0,    0,    0,
      397,  341,  334,    0,  995,  324,  313,  318,  311,    0,
      282,    0,  296,  314,    0,    0,  995,  280,    0,  255,

      253,  202,    0,  209,  179,  152,  145,  111,  995,  995,
      771,  780,  789,  798,  802,  811,  816,  124,  818,  822,
      831
    } ;

static const flex_int16_t yy_def[522] =
    {   0,
      510,    1,  511,  511,  512,  512,  510,  510,  510,  510,
      510,  510,  513,  510,  510,  514,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  515,  515,  510,  510,  510,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  516,  510,  510,  510,
      510,  510,  513,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,   93,  510,  510,  510,  510,  517,  510,

      510,   26,  510,  510,  510,  510,  510,  510,  510,  515,
      515,  515,  510,  510,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  510,
      510,  510,  510,  516,  510,  510,  510,  513,  513,  510,
      510,  510,  510,   88,  510,  510,  510,  510,  510,   93,
       93,  510,  510,  510,  510,  510,  510,  518,  519,   93,
      510,  102,  510,  102,  510,  510,  510,  515,  515,  515,

      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  510,  513,  513,  510,  510,  510,  510,  178,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  520,
      518,  519,  272,  510,  510,  272,  190,  190,  510,  510,
      510,  510,  194,  510,  510,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,

      515,  515,  515,  515,  515,  515,  515,  515,  515,  510,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  521,  521,  510,
      510,  510,  510,  510,  510,  510,  520,  520,  510,  510,
      510,  510,  510,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  510,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  510,  510,  510,  521,  510,

      521,  510,  510,  510,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  510,
      515,  515,  515,  515,  515,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  510,  510,  521,  510,
      510,  510,  510,  510,  521,  510,  515,  515,  515,  515,
      515,  515,  515,  515,  510,  515,  515,  515,  515,  515,
      515,  515,  515,  515,  515,  515,  510,  510,  510,  521,
      510,  515,  515,  515,  515,  510,  515,  515,  515,  515,
      515,  515,  515,  515,  510,  510,  515,  515,  510,  515,
      515,  515,  515,  510,  515,  515,  510,  515,  515,  510,

      515,  510,  515,  510,  510,  510,  510,  510,  510,    0,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510
    } ;

static const flex_int16_t yy_nxt[1068] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   26,
       26,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       34,   34,   34,   34,   34,   34,   35,   34,   36,    8,
       37,   38,   34,   39,   40,   41,   42,   43,   44,   34,
       34,   45,   34,   46,   47,   48,   49,   50,   34,   51,
       52,   53,   54,   55,   56,   34,   57,   34,   58,   59,
       60,   61,   63,   64,   63,   64,   66,   66,   69,   70,
       71,   70,   74,   77,   82,   67,   67,   84,   87,  243,
       88,   88,   88,   88,   88,   89,  115,   83,   85,   86,

       90,   78,  105,  106,  108,  109,  111,  120,  244,   91,
      121,  112,  116,  122,  155,  117,   75,   92,  118,   93,
       93,   93,   93,   94,  131,  119,  123,  156,  125,  270,
      132,  133,   95,   96,   97,  124,   98,  157,  158,   99,
      126,  136,  160,  127,  100,  137,  101,  241,   96,   97,
       96,  128,  151,  129,  138,  242,  130,  166,  152,  141,
      139,  153,  146,  142,  164,  147,  509,   99,   92,  165,
      102,  102,  102,  102,  102,  143,  148,  149,  144,   69,
       70,  150,   71,   70,   96,   97,  161,   98,   69,   70,
      211,   75,  185,  185,  212,  103,  191,  191,  508,   96,

       97,   96,   73,  196,  197,   73,  218,  219,  178,  178,
      178,  178,  178,  507,  168,  168,  168,  169,   94,   94,
       94,   94,   96,  179,  186,  247,  186,  248,  237,  187,
      187,  187,  187,  187,  506,  510,   73,   96,  179,   96,
      464,   73,  229,  184,  238,   73,  164,  230,  338,  339,
      304,  165,   73,  305,  465,  166,   73,   73,   73,   79,
      505,  504,   79,  190,  190,  190,  190,   94,  316,  275,
      317,  171,  171,  171,  172,  192,  192,  192,  192,  192,
      194,  194,  194,  194,  194,  170,  344,  344,  100,   75,
      232,  275,  439,   79,  255,  255,  255,  255,   79,  503,

      193,  438,   79,  233,  437,  103,  234,  351,  351,   79,
      166,  346,  502,   79,   79,   79,  174,  174,  174,  174,
      174,  166,  253,  253,  253,  253,  510,  501,  170,  500,
      175,  176,  353,  254,  254,  254,  254,  256,  256,  256,
      256,  177,  510,  499,   75,  175,  176,  175,   92,  498,
      180,  181,  180,  180,   94,   75,  275,  497,  174,  174,
      174,  174,  174,  348,   96,   97,  496,  182,  187,  187,
      187,  187,  187,  495,  440,  183,  510,  437,  275,   96,
       97,   96,  257,  177,  257,  494,  166,  258,  258,  258,
      258,  258,  259,  259,  259,  259,  259,  493,  254,  254,

      254,  254,  492,  261,  170,  261,   96,  179,  262,  262,
      262,  262,  262,  256,  256,  256,  256,  260,  263,  264,
       75,   96,  179,   96,  180,  180,  180,  180,   94,   94,
       94,   94,   94,   94,  470,  265,  267,  267,  267,  267,
      267,  344,  344,  266,  271,  280,  281,  273,  491,  183,
      268,  490,  344,  345,  184,  277,  278,  277,  277,  489,
      488,  269,  265,  274,  275,  268,  346,  268,  510,  265,
      282,  276,  192,  192,  192,  192,  192,  346,  351,  351,
      279,  283,  283,  283,  283,  283,  275,  258,  258,  258,
      258,  258,  259,  259,  259,  259,  259,  193,  340,  340,

      340,  340,  340,  353,  487,  485,  284,  262,  262,  262,
      262,  262,  175,  344,  345,  486,  437,  260,  342,  342,
      342,  342,  342,  341,  485,  397,  398,  175,  399,  175,
      265,  484,   96,  267,  267,  267,  267,  267,  346,  510,
      483,  271,  482,  343,  273,  401,  398,   96,  399,   96,
      267,  267,  267,  267,  267,  481,  275,  480,  269,  479,
      274,  275,  400,  348,  268,  349,  510,  349,  276,  272,
      350,  350,  350,  350,  350,  269,  351,  352,  275,  268,
      478,  268,  400,  275,  477,  510,  510,  277,  277,  277,
      277,   94,  476,  265,  351,  352,  283,  283,  283,  283,

      283,  353,  340,  340,  340,  340,  340,  475,  510,  474,
      510,  265,  279,  473,  472,  471,  175,  348,  437,  353,
      437,  284,  340,  340,  340,  340,  340,  341,  344,  345,
      437,  175,  510,  175,  342,  342,  342,  342,  342,  342,
      342,  342,  342,  342,  467,  265,  466,  341,   96,  344,
      345,  463,  462,  346,  350,  350,  350,  350,  350,  343,
      351,  352,  461,   96,  343,   96,  265,  402,  402,  402,
      402,  402,  351,  352,  346,  397,  398,  265,  445,  460,
      459,  403,  458,  457,  456,  353,  455,  454,  453,  265,
      452,  451,  404,  450,  449,  448,  403,  353,  403,  440,

      441,  447,  442,  446,  437,  442,  402,  402,  402,  402,
      402,  437,  400,  436,  443,  443,  443,  444,  435,  434,
      403,  402,  402,  402,  402,  402,  433,  432,  431,  430,
      429,  404,  428,  427,  426,  403,  442,  403,  425,  424,
      423,  442,  422,  421,  420,  442,  404,  437,  419,  418,
      417,  437,  442,  416,  415,  437,  442,  442,  442,  468,
      468,  468,  468,  469,  469,  469,  469,  469,  469,  469,
      469,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   73,
      414,  413,   73,   73,   73,   73,   73,   73,   79,  412,

      411,  410,   79,   79,   79,   79,   79,  110,  110,  110,
      110,  163,  409,  163,  163,  163,  163,  163,  163,  163,
      189,  189,  272,  272,  408,  272,  272,  347,  407,  406,
      347,  396,  396,  396,  396,  396,  396,  396,  396,  396,
      405,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  170,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,

      321,  320,  319,  318,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  252,  251,  250,  249,  246,  245,  240,
      239,  236,  235,  231,  228,  227,  226,  225,  224,  223,
      222,  221,  220,  217,  216,  215,  214,  213,  210,  209,
      208,  207,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  195,  188,  173,  170,  167,   68,  162,  159,  154,
      145,  140,  135,  134,  114,  113,  107,  104,   81,   80,
       76,   72,   68,  510,    7,  510,  510,  510,  510,  510,

      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510
    } ;

static const flex_int16_t yy_chk[1068] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    3,    4,    4,    5,    6,   10,   10,
       11,   11,   13,   15,   20,    5,    6,   22,   23,  153,
       23,   23,   23,   23,   23,   24,   39,   20,   22,   22,

       24,   15,   29,   29,   31,   31,   35,   41,  153,   24,
       41,   35,   39,   41,   55,   40,   13,   25,   40,   25,
       25,   25,   25,   25,   45,   40,   42,   55,   43,  518,
       45,   45,   25,   25,   25,   42,   25,   56,   56,   25,
       43,   48,   59,   44,   25,   48,   25,  151,   25,   25,
       25,   44,   53,   44,   48,  151,   44,   73,   53,   50,
       48,   53,   52,   50,   67,   52,  508,   25,   26,   67,
       26,   26,   26,   26,   26,   50,   52,   52,   50,   69,
       69,   52,   70,   70,   26,   26,   59,   26,   71,   71,
      126,   73,   95,   95,  126,   26,  101,  101,  507,   26,

       26,   26,   75,  109,  109,   75,  133,  133,   92,   92,
       92,   92,   92,  506,   75,   75,   75,   75,   94,   94,
       94,   94,   92,   92,   97,  156,   97,  156,  148,   97,
       97,   97,   97,   97,  505,   94,   75,   92,   92,   92,
      435,   75,  143,   94,  148,   75,  164,  143,  252,  252,
      217,  164,   75,  217,  435,  254,   75,   75,   75,   80,
      504,  502,   80,  100,  100,  100,  100,  100,  230,  271,
      230,   80,   80,   80,   80,  102,  102,  102,  102,  102,
      103,  103,  103,  103,  103,  171,  266,  266,  100,  254,
      145,  271,  399,   80,  171,  171,  171,  171,   80,  501,

      102,  398,   80,  145,  398,  103,  145,  282,  282,   80,
      168,  266,  500,   80,   80,   80,   88,   88,   88,   88,
       88,  169,  168,  168,  168,  168,  399,  498,  172,  494,
       88,   88,  282,  169,  169,  169,  169,  172,  172,  172,
      172,   88,  439,  493,  168,   88,   88,   88,   93,  491,
       93,   93,   93,   93,   93,  169,  270,  489,  177,  177,
      177,  177,  177,  270,   93,   93,  488,   93,  186,  186,
      186,  186,  186,  487,  441,   93,  439,  441,  270,   93,
       93,   93,  176,  177,  176,  486,  253,  176,  176,  176,
      176,  176,  178,  178,  178,  178,  178,  483,  253,  253,

      253,  253,  482,  179,  255,  179,  178,  178,  179,  179,
      179,  179,  179,  255,  255,  255,  255,  178,  185,  185,
      253,  178,  178,  178,  183,  183,  183,  183,  183,  184,
      184,  184,  184,  184,  445,  185,  187,  187,  187,  187,
      187,  346,  346,  185,  189,  191,  191,  189,  481,  183,
      187,  477,  263,  263,  184,  190,  190,  190,  190,  476,
      475,  187,  191,  189,  189,  187,  346,  187,  445,  263,
      191,  189,  193,  193,  193,  193,  193,  263,  353,  353,
      190,  194,  194,  194,  194,  194,  189,  257,  257,  257,
      257,  257,  260,  260,  260,  260,  260,  193,  258,  258,

      258,  258,  258,  353,  474,  470,  194,  261,  261,  261,
      261,  261,  258,  264,  264,  471,  469,  260,  262,  262,
      262,  262,  262,  258,  467,  338,  338,  258,  338,  258,
      264,  466,  262,  269,  269,  269,  269,  269,  264,  470,
      465,  272,  464,  262,  272,  339,  339,  262,  339,  262,
      267,  267,  267,  267,  267,  463,  347,  462,  269,  461,
      272,  272,  338,  347,  267,  275,  276,  275,  272,  276,
      275,  275,  275,  275,  275,  267,  280,  280,  347,  267,
      460,  267,  339,  272,  459,  276,  276,  279,  279,  279,
      279,  279,  455,  280,  281,  281,  284,  284,  284,  284,

      284,  280,  340,  340,  340,  340,  340,  454,  276,  453,
      348,  281,  279,  449,  447,  446,  340,  348,  442,  281,
      440,  284,  341,  341,  341,  341,  341,  340,  344,  344,
      438,  340,  348,  340,  342,  342,  342,  342,  342,  343,
      343,  343,  343,  343,  437,  344,  436,  341,  342,  345,
      345,  433,  432,  344,  349,  349,  349,  349,  349,  342,
      351,  351,  428,  342,  343,  342,  345,  350,  350,  350,
      350,  350,  352,  352,  345,  401,  401,  351,  401,  425,
      424,  350,  423,  422,  421,  351,  420,  417,  415,  352,
      414,  413,  350,  411,  410,  409,  350,  352,  350,  400,

      400,  407,  400,  406,  397,  400,  402,  402,  402,  402,
      402,  396,  401,  393,  400,  400,  400,  400,  392,  391,
      402,  404,  404,  404,  404,  404,  390,  388,  387,  385,
      384,  402,  383,  382,  381,  402,  400,  402,  380,  379,
      378,  400,  377,  376,  374,  400,  404,  443,  373,  372,
      371,  444,  400,  370,  369,  468,  400,  400,  400,  443,
      443,  443,  443,  444,  444,  444,  444,  468,  468,  468,
      468,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      512,  512,  512,  512,  512,  512,  512,  512,  512,  513,
      365,  364,  513,  513,  513,  513,  513,  513,  514,  363,

      362,  361,  514,  514,  514,  514,  514,  515,  515,  515,
      515,  516,  358,  516,  516,  516,  516,  516,  516,  516,
      517,  517,  519,  519,  357,  519,  519,  520,  356,  355,
      520,  521,  521,  521,  521,  521,  521,  521,  521,  521,
      354,  337,  335,  334,  330,  329,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  318,  317,  316,  315,  314,
      313,  312,  310,  309,  308,  306,  305,  304,  303,  302,
      301,  300,  299,  297,  296,  295,  294,  291,  290,  289,
      288,  287,  286,  256,  251,  250,  249,  248,  247,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,

      234,  233,  232,  231,  229,  228,  227,  226,  225,  224,
      222,  221,  220,  218,  215,  214,  213,  212,  211,  210,
      209,  208,  207,  206,  205,  204,  203,  202,  201,  200,
      199,  198,  197,  167,  159,  158,  157,  155,  154,  150,
      149,  147,  146,  144,  142,  141,  140,  139,  138,  137,
      136,  135,  134,  132,  130,  129,  128,  127,  125,  124,
      123,  122,  121,  120,  119,  118,  117,  116,  115,  112,
      111,  105,   99,   87,   79,   74,   68,   64,   57,   54,
       51,   49,   47,   46,   38,   36,   30,   27,   19,   16,
       14,   12,    9,    7,  510,  510,  510,  510,  510,  510,

      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510,  510,  510,  510,
      510,  510,  510,  510,  510,  510,  510
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[131] =
    {   0,
1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tokenizer.l"
#line 2 "tokenizer.l"
    #include <stdlib.h>
    #include <string.h>
    #include "y.tab.h"
    #include "symbols.h"
    #include "types.h"
    extern SymGlob* root;
    extern TypeHandler* typeroot;
    extern map<string,SymNode*> list_class;
    extern void yyerror(const char*sp);
    extern int importflag;
    extern int isarrayinit;
    int fin=0;
#line 895 "lex.yy.c"

#line 897 "lex.yy.c"

#define INITIAL 0
#define COMMENT1 1
#define COMMENT2 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 103 "tokenizer.l"


#line 1119 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 511 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 995 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 105 "tokenizer.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 106 "tokenizer.l"
{/* ignore whitespace  */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 108 "tokenizer.l"
BEGIN(COMMENT1);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 109 "tokenizer.l"
/* ignore anything except a  line */
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 110 "tokenizer.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 112 "tokenizer.l"
BEGIN(COMMENT2);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 113 "tokenizer.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 114 "tokenizer.l"

	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 115 "tokenizer.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 116 "tokenizer.l"
BEGIN(INITIAL);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 118 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BOOLEAN;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 119 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return CHAR;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 120 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BYTE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 121 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return SHORT;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 122 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return INT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 123 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LONG;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return FLOAT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DOUBLE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return VOID;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 127 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return EXTENDS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return SUPER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 129 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return THIS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 130 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return INSTANCEOF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 131 "tokenizer.l"
{fin=1;yylval.lexeme = strdup(yytext); return FINAL;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 132 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NEW;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 133 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return STRING;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 134 "tokenizer.l"
{   
                    root->addNewScope();
                    if(fin==1){
                        fin=0;
                        root->currNode->isFinalClass=true;
                    }
                    root->currNode->name="class";
                    root->currNode->isClassName=false;
                    yylval.lexeme = strdup(yytext);
                    return CLASS;
                }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 145 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PACKAGE;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 146 "tokenizer.l"
{yylval.lexeme = strdup(yytext); importflag=1; return IMPORT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 147 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return IMPLEMENTS;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return STATIC;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 149 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return TRANSIENT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 150 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PUBLIC;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 151 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PROTECTED;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 152 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PRIVATE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 153 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return ABSTRACT;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 154 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DEFAULT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 155 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return VOLATILE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 156 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return SYNCHRONIZED;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 157 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NATIVE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 158 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return STRICTFP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 159 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return THROWS;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 160 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return ASSERT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 161 "tokenizer.l"
{root->addNewScope();root->currNode->vulnerable=true;root->currNode->isIfScope=true;root->currNode->name="if";yylval.lexeme = strdup(yytext); return IF;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 162 "tokenizer.l"
{root->addNewScope();root->currNode->vulnerable=true;root->currNode->name="else";yylval.lexeme = strdup(yytext); return ELSE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 163 "tokenizer.l"
{root->addNewScope();root->currNode->vulnerable=true;root->currNode->name="while";yylval.lexeme = strdup(yytext); return WHILE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 164 "tokenizer.l"
{root->addNewScope();root->currNode->vulnerable=true;root->currNode->isForScope=true;root->currNode->name="for";yylval.lexeme = strdup(yytext); return FOR;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 165 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return RETURN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 166 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return CONTINUE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 167 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BREAK;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 168 "tokenizer.l"
{root->addNewScope();root->currNode->name="do";yylval.lexeme = strdup(yytext); return DO;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 169 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return BOOLEANLITERAL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 170 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BOOLEANLITERAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 174 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return EXPORTS;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 175 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return OPENS;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 176 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return USES;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 177 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return REQUIRES;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 178 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return YIELD;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 179 "tokenizer.l"
{root->addNewScope();yylval.lexeme = strdup(yytext); return MODULE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 180 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return SEALED;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 181 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NONSEALED;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 182 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PERMITS;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 183 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return VAR;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 184 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return TO;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 185 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PROVIDES;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 186 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return WITH;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 187 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return TRANSITIVE;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 188 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return OPEN;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 189 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return RECORD;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 190 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NULLLITERAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 191 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return SYSTEMOUTPRINTLN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 192 "tokenizer.l"
{   
                    if((root->currNode->name=="class"||root->currNode->name=="classextends")&&
                    root->currNode->isClassName==false){
                        SymNode* res = root->currNode->scope_clookup(yytext);
                        if(res)
                        {
                            yyerror("Class already declared.");
                        }
                        res = new SymNode(root->currNode, "class", CLASS_SYM);
                        root->cinsert(yytext, res);
                        Symbol* r = new Symbol(yytext, typeroot->addNewClassType(yytext), yylineno);
                        root->par_insert(r->lexeme, r);
                        list_class[yytext]=root->currNode;
                        root->currNode->isClassName=true;
                    }
                    yylval.lexeme = strdup(yytext);
                    return IDENTIFIER;
                }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 210 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LRSQUAREBRACKET;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 211 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LEFTSQUAREBRACKET;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 212 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return RIGHTSQUAREBRACKET;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 213 "tokenizer.l"
{
                    yylval.lexeme = strdup(yytext);
                    return LEFTPARENTHESIS;
                }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 217 "tokenizer.l"
{
                    if(root->currNode->isForScope){
                        root->currNode->isRightPar=true;
                    }
                    yylval.lexeme = strdup(yytext);
                    return RIGHTPARENTHESIS;
                }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 224 "tokenizer.l"
{   
                        if(root->currNode->name=="classextends" && root->currNode->parent->default_done==0 && root->currNode->parent->constr_args.size()>0 && root->currNode->constr_args.size()==0)
                        {
                            cout<<"Error on line number "<<yylineno<<". This class must include an explicit constructor declaration"<<endl;
                            yyerror("Error");
                        }
                        if(isarrayinit==0){
                        if(root->currNode->vulnerable==false&&
                        root->currNode->isIfScope==true){
                            root->endcurrScope();
                            root->currNode->isThisDead=true;
                        }
                        else
                        if(root->currNode->vulnerable==false&&
                        root->currNode->isIfScope==false){
                            root->end_all_vulnerable();
                        }
                    }
                    else{
                        isarrayinit--;
                    }
                    yylval.lexeme = strdup(yytext); 
                    return RIGHTCURLYBRACKET;
                }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 248 "tokenizer.l"
{
                    root->currNode->vulnerable=false;
                    yylval.lexeme = strdup(yytext);
                    return LEFTCURLYBRACKET;
                }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 253 "tokenizer.l"
{
                    if(root->currNode->vulnerable==true&&
                    root->currNode->isIfScope==true){
                        root->endcurrScope();
                        root->currNode->isThisDead=true;
                    }
                    else
                    if(root->currNode->vulnerable==true&&
                    root->currNode->isIfScope==false&&
                    root->currNode->isForScope==true&&
                    root->currNode->isRightPar==true){
                        root->end_all_vulnerable();
                    }
                    else
                    if(root->currNode->vulnerable==true&&
                    root->currNode->isIfScope==false&&
                    root->currNode->isForScope==false){
                        root->end_all_vulnerable();
                    }
                    yylval.lexeme = strdup(yytext);
                    return SEMICOLON;
                }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 275 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return COMMA;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 276 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return ELLIPSIS;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 277 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DOT;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 278 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return AT;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 279 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DOUBLECOLON;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 280 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return ASSIGN;}  
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 281 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return GRT;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 282 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LSS;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 283 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NOT;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 284 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return TIL;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 285 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return QUES;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 286 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return COL;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 287 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return ARW;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 288 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return EQUAL;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 289 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return GEQ;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 290 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LEQ;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 291 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return NEQUAL;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 292 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return AND;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 293 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return OR;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 294 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return INCRE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 295 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DECRE;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 296 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PLUS;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 297 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MINUS;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 298 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MULT;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 299 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DIV;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 300 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BAND;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 301 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BOR;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 302 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BXOR;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 303 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MOD;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 304 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LSHIFT;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 305 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return RSHIFT;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 306 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return UNRSHIFT;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 307 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return PLUSEQUAL;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 308 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MINUSEQUAL;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 309 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MULTEQUAL;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 310 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return DIVEQUAL;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 311 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BANDEQUAL;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 312 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BOREQUAL;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 313 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return BXOREQUAL;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 314 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return MODEQUAL;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 315 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return LSHIFTEQUAL;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 316 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return RSHIFTEQUAL;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 317 "tokenizer.l"
{yylval.lexeme = strdup(yytext); return UNRSHIFTEQUAL;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 318 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return INTEGERLITERAL;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 319 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return FLOATINGPOINTLITERAL;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 320 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return STRINGLITERAL;}           
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 321 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return CHARACTERLITERAL;}
	YY_BREAK
case 128:
/* rule 128 can match eol */
YY_RULE_SETUP
#line 322 "tokenizer.l"
{yylval.lexeme = strdup(yytext);return TEXTBLOCK;}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 323 "tokenizer.l"
{printf("Unrecognized character: %s at line no %d\n", yytext, yylineno); return 0;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 324 "tokenizer.l"
ECHO;
	YY_BREAK
#line 1924 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT1):
case YY_STATE_EOF(COMMENT2):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 511 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 511 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 510);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 324 "tokenizer.l"


